services:
  - type: web
    name: cccji
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
